##SET ROLE
PUT http://localhost:3000/users/set-role/ff29515f-598b-4eb0-b49a-cbd07e61b486
Content-Type: application/json

{
    "Role": "user"
}


###
## Create  User
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "Username":"Kenedy Maina",
    "Email": "kennynet66@yopmail.com",
    "Phone_number": "0750339662",
    "Password": "123456789"
   
}

###

POST  http://localhost:3000/users/login
Content-Type: application/json

{
    "Email": "sharoncherotich@gmail.com",
    "Password": "sharon12"
}

# GET ALL USERS
###
GET  http://localhost:3000/users/getAllUsers
Content-Type: application/json

#GET ONE USER
###
GET http://localhost:3000/users/getOneUser/3b999ac9-2ebf-43d3-8517-20cd60795678
Content-Type: application/json

##UPDATE USER
###
POST http://localhost:3000/users/updateUser/4efbb10d-8050-4e70-8061-700d05ecbebe
Content-Type: application/json

{
    "Username":"Sharon Cherotich",
    "Email": "sharoncherotich@gmail.com",
    "Phone_number": "0716013980"
   
}

##DELETE USER
###
DELETE http://localhost:3000/users/deleteUser/43856818-6097-418a-96c3-16a998c7c62d
Content-Type: application/json