##SET ROLE
PUT http://localhost:3000/users/set-role/ff29515f-598b-4eb0-b49a-cbd07e61b486
Content-Type: application/json

{
    "Role": "user"
}

##SAVE SPECIALIST INFO
###
POST http://localhost:3000/users/specialist/7203a94c-1c97-4c91-a74c-51b41e8d942a
Content-Type: application/json

{
    "First_Name": "Amanda",
    "Last_Name": "Cherotich",
    "Speciality": "Designer",
    "Rate": 4500,
    "Description": "This is another too description"
}


###
## Create  User
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "Username":"Kenedy Maina",
    "Email": "kennynet66@yopmail.com",
    "Phone_number": "0750339662",
    "Password": "123456789"
   
}

###

POST  http://localhost:3000/users/login
Content-Type: application/json

{
    "Email": "sharoncherotich@gmail.com",
    "Password": "sharon12"
}

# GET ALL USERS
###
GET  http://localhost:3000/users/getAllUsers
Content-Type: application/json

#GET ONE USER
###
GET http://localhost:3000/users/getOneUser/c030bd85-d78f-4606-8b8d-d1a47f5e715d
Content-Type: application/json

##UPDATE USER
###
POST http://localhost:3000/users/updateUser/4efbb10d-8050-4e70-8061-700d05ecbebe
Content-Type: application/json

{
    "Username":"Sharon Cherotich",
    "Email": "sharoncherotich@gmail.com",
    "Phone_number": "0716013980"
   
}

##DELETE USER
###
DELETE http://localhost:3000/users/deleteUser/a13f4585-e2da-4018-a716-f1b5c4517baa
Content-Type: application/json

##GET SPECIALIST INFO
###
GET http://localhost:3000/users/specialistInfo/ebedff33-11d3-4633-98ee-abba9f54484d
Content-Type: application/json