POST http://localhost:3000/category/createCategory
Content-Type: application/json

{
    "categoryname": "Programming",
    "image": "https://images.pexels.com/photos/1181677/pexels-photo-1181677.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
}

# GET ALL CATEGORIES
###
GET http://localhost:3000/category/getAllCategories
Content-Type: application/json

#GET ONE CATEGORY
###
GET http://localhost:3000/category/getOnecategory/a018ce97-f4cf-425c-b0f1-60301c73b33e
Content-Type: application/json

#UPDATE CATEGORY
###
PUT http://localhost:3000/category/updateCategory/34a81881-29d3-4b8a-b5f7-64fa871b425c
Content-Type: application/json

{
    "categoryname": "Design3",
    "image": "https://images.pexels.com/photos/326502/pexels-photo-326502.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
}

#DELETE CATEGORY
###
DELETE  http://localhost:3000/category/deleteCategory/a018ce97-f4cf-425c-b0f1-60301c73b33e
Content-Type: application/json