POST http://localhost:3000/category/createCategory
Content-Type: application/json

{
    "categoryname": "CareGiving",
    "image": "https://images.pexels.com/photos/8127503/pexels-photo-8127503.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
}

# GET ALL CATEGORIES
###
GET http://localhost:3000/category/getAllCategories
Content-Type: application/json

#GET ONE CATEGORY
###
GET http://localhost:3000/category/getOnecategory/1e755b75-8eed-4dae-839b-f46df6512cd0
Content-Type: application/json

#UPDATE CATEGORY
###
PUT http://localhost:3000/category/updateCategory/34a81881-29d3-4b8a-b5f7-64fa871b425c
Content-Type: application/json

{
    "categoryname": "Programming",
    "image": "https://images.pexels.com/photos/270366/pexels-photo-270366.jpeg?auto=compress&cs=tinysrgb&w=600"
}

#GETSPECIALISTBYCATEGORYID
###
GET http://localhost:3000/category/categorySpecialists/1e755b75-8eed-4dae-839b-f46df6512cd0
Content-Type: application/json

#DELETE CATEGORY
###
DELETE  http://localhost:3000/category/deleteCategory/a018ce97-f4cf-425c-b0f1-60301c73b33e
Content-Type: application/json