POST http://localhost:3000/gigs/createGig/dgagychxbnopacifyvhbjx/876edftcyghjoisvug
Content-Type: application/json

{
    "Description": "This is the second gig",
    "Deadline": "2/3/2024",
    "Salary": 20000,
    "Duration": "3 days"
}

##GET ALL GIGS
###
GET http://localhost:3000/gigs/getAllGigs
Content-Type: application/json

##GET ONE GIG
###
GET http://localhost:3000/gigs/getOneGig/05b2cc88-c77c-45da-a790-ac1bd4cd6495
Content-Type: application/json

##UPDATE GIG
###
PUT http://localhost:3000/gigs/updateGig/05b2cc88-c77c-45da-a790-ac1bd4cd6495
Content-Type: application/json

{
    "user_id": "dgagychxbnopacifyvhbjx",
    "Specialists_id": "876edftcyghjoisvug",
    "Description": "This is the Second gig",
    "Deadline": "2/3/2024",
    "Salary": 10000,
    "Duration": "5 days"
}

##DELETE GIG
###
DELETE http://localhost:3000/gigs/deleteGig/ca16dcdf-4fd2-4b87-b848-98f70dc7f4d3
Content-Type: application/json

##GETSPECIALISTSGIG
###
GET http://localhost:3000/gigs/gigSpecialists/c030bd85-d78f-4606-8b8d-d1a47f5e715d
Content-Type: application/json