##CREATE A REVIEW
POST http://localhost:3000/reviews/createReview/cdftvgybunhjimkfg/drtfgyuhnjimkfgh
Content-Type: application/json

{
    "Stars": 5,
    "Review": "This is the first review"
}

##GET ALL REVIEWS
###
GET http://localhost:3000/reviews/getAllReviews
Content-Type: application/json

##GET ONE REVIEW
###
GET http://localhost:3000/reviews/getOneReview/2acea1cd-53c0-4dda-abee-197c79b641a2
Content-Type: application/json

###DELETE REVIEW
###
DELETE http://localhost:3000/reviews/deleteReview/28322f12-fbc9-4053-867d-97e0dd4bef35
Content-Type: application/json

###SPECIALIST REVIEW
###
GET http://localhost:3000/reviews/specialistReview/c030bd85-d78f-4606-8b8d-d1a47f5e715d
Content-Type: application/json