POST http://localhost:3000/reviews/createReview
Content-Type: application/json

{
   " user_id": "iuf88yfvjha90fy9vkas0hs7f",
    "Specialists_id":"huisdbgksb4345bxvskld",
    "review": "This is the first review"
}

## GET ALL REVIEWS
###
GET  http://localhost:3000/reviews/getAllReviews
Content-Type: application/json

##GET ONE REVIEW
###
GET http://localhost:3000/reviews/getOneReview/fdf5bfd1-1769-43ed-aa9b-0c6a2e41b3a2
Content-Type: application/json

##DELETE REVIEW
###
DELETE http://localhost:3000/reviews/deleteReview/cc132d45-0d7f-46c4-914f-b204e59eded4
Content-Type: application/json